//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Galleries = new HashSet<Gallery>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string ProductName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<double> Price { get; set; }
        public string ImgPath { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> HotProducts { get; set; }
        public Nullable<bool> NewArrivals { get; set; }
        public Nullable<bool> PolularProducts { get; set; }
        public Nullable<bool> Sale { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ProductRating { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Size Size { get; set; }
        public virtual Sub_categories Sub_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gallery> Galleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
